src/Entity/Milestone.php
<?php

namespace App\Entity;

use App\Repository\MilestoneRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MilestoneRepository::class)]
class Milestone
{

    public const STATE_TO_PLANE = 1;
    public const STATE_DONE = 2;
    public const STATE_IN_PROGRESS = 3;
    public const STATE_FORWARDED = 4;
    public const STATE_SIGNED = 5;
    public const STATE_TO_DO = 6;

    public const STATE_LABEL = [
        1 => "À planifier",
        2 => "Fait",
        3 => "En cours",
        4 => "Transmis",
        5 => "Signé",
        6 => "À faire",
    ];

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\Column(type: 'date_immutable', nullable: true)]
    private $date;

    #[ORM\Column(type: 'text', nullable: true)]
    private $description;

    #[ORM\Column(type: 'datetime_immutable')]
    private $createdAt;

    #[ORM\ManyToOne(targetEntity: User::class)]
    private $createdBy;

    #[ORM\Column(type: 'datetime_immutable')]
    private $updatedAt;

    #[ORM\ManyToOne(targetEntity: User::class)]
    private $updatedBy;

    #[ORM\Column(type: 'boolean')]
    private $isFinal;

    #[ORM\ManyToOne(targetEntity: Project::class, inversedBy: 'milestones')]
    #[ORM\JoinColumn(nullable: false)]
    private $project;

    #[ORM\Column(type: 'integer')]
    private $state = self::STATE_TO_DO;

    #[ORM\Column(type: 'boolean')]
    private $finished = false;

    public function __construct()
    {
        $this->setIsFinal(false);
        $this->setCreatedAt(new \DateTimeImmutable());
        $this->setUpdatedAt(new \DateTimeImmutable());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStateLabel(): string
    {
        return self::STATE_LABEL[$this->getState()];
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDate(): ?\DateTimeImmutable
    {
        return $this->date;
    }

    public function setDate($date): self
    {
        if($date instanceof \DateTime) {
            $date = \DateTimeImmutable::createFromMutable($date);
        }
        $this->date = $date;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCreatedBy(): ?User
    {
        return $this->createdBy;
    }

    public function setCreatedBy($createdBy): self
    {
        $this->createdBy = $createdBy;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getUpdatedBy(): ?User
    {
        return $this->updatedBy;
    }

    public function setUpdatedBy($updatedBy): self
    {
        $this->updatedBy = $updatedBy;

        return $this;
    }

    public function getIsFinal(): ?bool
    {
        return $this->isFinal;
    }

    public function setIsFinal(bool $isFinal): self
    {
        $this->isFinal = $isFinal;

        return $this;
    }

    public function __toString(): string
    {
        return $this->getName();
    }

    public function getProject(): ?Project
    {
        return $this->project;
    }

    public function setProject(?Project $project): self
    {
        $this->project = $project;

        return $this;
    }

    public function getState(): ?int
    {
        return $this->state;
    }

    public function setState(int $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getFinished(): ?bool
    {
        return $this->finished;
    }

    public function setFinished(bool $finished): self
    {
        $this->finished = $finished;

        return $this;
    }
}

src/Entity/Project.php
<?php

namespace App\Entity;

use App\Repository\ProjectRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: ProjectRepository::class)]
class Project
{

    public const STATE_IN_PROGRESS = 1;
    public const STATE_STANDBY = 2;
    public const STATE_CANCELED = 3;
    public const STATE_FINISHED = 4;

    public const MANDATE_RELATED_STATE = [
        self::STATE_IN_PROGRESS => Mandate::STATE_ACTIVE,
        self::STATE_STANDBY => Mandate::STATE_ACTIVE,
        self::STATE_CANCELED => Mandate::STATE_CANCEL,
        self::STATE_FINISHED => Mandate::STATE_TERMINATED,
    ];

    public const STATE_ICONS = [
        self::STATE_IN_PROGRESS => 'flash',
        self::STATE_STANDBY => 'pause-circle',
        self::STATE_CANCELED => 'x-octagon',
        self::STATE_FINISHED => 'check-circle'
    ];

    public const STATE_COLOR = [
        self::STATE_IN_PROGRESS => 'text-warning',
        self::STATE_STANDBY => 'text-secondary',
        self::STATE_CANCELED => 'text-muted',
        self::STATE_FINISHED => 'text-primary'
    ];

    public const STATE_LABEL = [
        self::STATE_IN_PROGRESS => "En cours",
        self::STATE_STANDBY => "En pause",
        self::STATE_CANCELED => "Annulé",
        self::STATE_FINISHED => "Terminé",
     ];

    public const STATE_SLUG = [
        self::STATE_IN_PROGRESS => "in-progress",
        self::STATE_STANDBY => "pause",
        self::STATE_CANCELED => "cancel",
        self::STATE_FINISHED => "finished",
    ];


    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'datetime_immutable')]
    private $createdAt;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'createdProjects')]
    private $createdBy;

    #[ORM\Column(type: 'datetime_immutable')]
    private $updatedAt;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'updatedProjects')]
    private $updatedBy;

    #[ORM\OneToMany(mappedBy: 'project', targetEntity: Milestone::class, cascade: ['persist', 'remove'], orphanRemoval: true)]
    private $milestones;

    #[ORM\ManyToOne(targetEntity: Mandate::class, inversedBy: 'projects')]
    private $mandate;

    #[ORM\ManyToOne(targetEntity: Person::class, inversedBy: 'supervisedProjects')]
    private $coach;

    #[ORM\Column(type: 'date', nullable: true)]
    private $specificationsEndDate = null;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $state = self::STATE_IN_PROGRESS;

    #[ORM\ManyToOne(targetEntity: Classe::class, inversedBy: 'projects')]
    private $class;

    #[ORM\OneToMany(mappedBy: 'project', targetEntity: Member::class, orphanRemoval: true)]
    private $members;

    #[ORM\OneToMany(mappedBy: 'project', targetEntity: File::class)]
    private $files;

    #[ORM\OneToMany(mappedBy: 'project', targetEntity: Note::class, cascade: ['persist', 'remove'], orphanRemoval: true)]
    private $teacherEvaluation;

    #[ORM\OneToOne(mappedBy: 'project', targetEntity: ClientEvaluation::class, cascade: ['persist', 'remove'], orphanRemoval: true)]
    private $clientEvaluation;

    #[ORM\Column(type: 'integer')]
    private $code;

    public function __construct()
    {
        $this->setCreatedAt(new \DateTimeImmutable());
        $this->setUpdatedAt(new \DateTimeImmutable());
        $this->milestones = new ArrayCollection();
        $this->members = new ArrayCollection();
        $this->files = new ArrayCollection();
        $this->teacherEvaluation = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStatus()
    {
        return self::STATE_LABEL[$this->getState()];
    }

    public function getUid(): string
    {
        return $this->getMandate()->getUid();
    }

    public function getClient()
    {
        return $this->getMandate()->getClient();
    }

    public function getDescription()
    {
        return $this->getMandate()->getDescription();
    }

    public function getTitle()
    {
        return $this->getMandate()->getTitle();
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCreatedBy(): ?User
    {
        return $this->createdBy;
    }

    public function setCreatedBy(User|UserInterface $createdBy): self
    {
        $this->createdBy = $createdBy;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getUpdatedBy(): ?User
    {
        return $this->updatedBy;
    }

    public function setUpdatedBy(User|UserInterface $updatedBy): self
    {
        $this->updatedBy = $updatedBy;

        return $this;
    }

    /**
     * @return Collection<int, Milestone>
     */
    public function getMilestones(): Collection
    {
        return $this->milestones;
    }

    public function addMilestone(Milestone $milestone): self
    {
        if (!$this->milestones->contains($milestone)) {
            $this->milestones[] = $milestone;
            $milestone->setProject($this);
        }

        return $this;
    }

    public function removeMilestone(Milestone $milestone): self
    {
        if ($this->milestones->removeElement($milestone)) {
            // set the owning side to null (unless already changed)
            if ($milestone->getProject() === $this) {
                $milestone->setProject(null);
            }
        }

        return $this;
    }

    public function getCoach(): ?Person
    {
        return $this->coach;
    }

    public function setCoach(?Person $coach): self
    {
        $this->coach = $coach;

        return $this;
    }

    public function getMandate(): ?Mandate
    {
        return $this->mandate;
    }

    public function setMandate(?Mandate $mandate): self
    {
        $this->mandate = $mandate;

        return $this;
    }

    public function getSpecificationsEndDate(): ?\DateTimeInterface
    {
        return $this->specificationsEndDate;
    }

    public function setSpecificationsEndDate(\DateTimeInterface $specificationsEndDate): self
    {
        $this->specificationsEndDate = $specificationsEndDate;

        return $this;
    }


    public function getState(): ?int
    {
        return $this->state;
    }

    public function setState(?int $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getClass(): ?Classe
    {
        return $this->class;
    }

    public function setClass(?Classe $class): self
    {
        $this->class = $class;

        return $this;
    }

    public function userIsMember(User $user): bool
    {
        $o = false;
        foreach ($this->getMembers() as $member) {
            if (!$o && $member->getUser() === $user) {
                $o = true;
            }
        }
        return $o;
    }

    public function getManager(): ?Member
    {
        foreach ($this->getMembers() as $member) {
            if($member->getIsProjectManager()) return $member;
        }
        return null;
    }

    /**
     * @return Collection<int, Member>
     */
    public function getMembers(): Collection
    {
        return $this->members;
    }

    public function addMember(Member $member): self
    {
        if (!$this->members->contains($member)) {
            $this->members[] = $member;
            $member->setProject($this);
        }

        return $this;
    }

    public function removeMember(Member $member): self
    {
        if ($this->members->removeElement($member)) {
            // set the owning side to null (unless already changed)
            if ($member->getProject() === $this) {
                $member->setProject(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->getTitle();
    }

    /**
     * @return Collection<int, File>
     */
    public function getFiles(): Collection
    {
        return $this->files;
    }

    public function addFile(File $file): self
    {
        if (!$this->files->contains($file)) {
            $this->files[] = $file;
            $file->setProject($this);
        }

        return $this;
    }

    public function removeFile(File $file): self
    {
        if ($this->files->removeElement($file)) {
            // set the owning side to null (unless already changed)
            if ($file->getProject() === $this) {
                $file->setProject(null);
            }
        }

        return $this;
    }

    public function getDuration()
    {
        if(is_null($this->getSpecificationsEndDate())) return null;
        return $this->getSpecificationsEndDate()->diff($this->getCreatedAt());
    }

    public function getOffset()
    {
        $startY = new \DateTime("2021-08-01");
        return $this->getCreatedAt()->diff($startY);
    }

    public static function STATES()
    {
        $out = [];
        foreach (self::STATE_SLUG as $key => $value) {
            $out[$key] = [
                'slug' => $value,
                'label' => self::STATE_LABEL[$key],
                'color' => self::STATE_COLOR[$key],
                'icon' => self::STATE_ICONS[$key]
            ];
        }
        return $out;
    }

    /**
     * @return Collection<int, Note>
     */
    public function getTeacherEvaluation(): Collection
    {
        return $this->teacherEvaluation;
    }

    public function addTeacherEvaluation(Note $teacherEvaluation): self
    {

templates/projects/_file_form.html.twig
{{ form_start(form) }}
    {{ form_row(form.title) }}
    {{ form_row(form.file) }}
    <button class="btn btn-primary">Enregistrer</button>
{{ form_end(form) }}

templates/projects/_member_form.html.twig
{{ form_start(form) }}
    {{ form_row(form.user) }}
    {{ form_row(form.title) }}
    {{ form_row(form.isProjectManager) }}
    <button class="btn btn-primary">Enregistrer</button>
{{ form_end(form) }}

templates/projects/_milestone_form.html.twig
{{ form_start(form) }}
    {{ form_row(form.name) }}
    {{ form_row(form.date) }}
    {{ form_row(form.description) }}
    {{ form_row(form.isFinal) }}
    {{ form_row(form.state) }}
    {{ form_row(form.finished) }}
    <button class="btn btn-primary">Modifier</button>
{{ form_end(form) }}

templates/projects/coach_eval.html.twig
{% extends 'base.html.twig' %}

{% set hasNavTabs = true %}
{% form_theme form 'bootstrap_5_horizontal_layout.html.twig' %}

{% block title %}{{ project.uid }} — {{ project.title }}{% endblock %}

{% block navTabs %}
    {{ include('partials/_project_nav_header.html.twig') }}
{% endblock %}

{% block body %}
    <div class="w-75 mx-auto mt-5">
        <h2 class="h1 mb-5">Évaluation final du projet</h2>
        {{ form_start(form, ) }}
            {% for note in form.teacherEvaluation %}
                <fieldset>
                    <legend>{{ note.name.vars.value }}</legend>
                    {{ form_row(note.name) }}
                    {{ form_row(note.value) }}
                    {{ form_row(note.comment) }}
                </fieldset>
            {% endfor %}
        <button class="btn btn-primary">Enregistrer</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/projects/file_add.html.twig
{% extends 'base.html.twig' %}

{% set hasNavTabs = true %}

{% block title %}{{ project.uid }} — {{ project.title }}{% endblock %}

{% block navTabs %}
    {{ include('partials/_project_nav_header.html.twig') }}
{% endblock %}

{% block body %}
    <div class="w-75 mx-auto mt-5">
        <h2 class="h1 mb-5">Ajouter un fichier</h2>
        {{ include('projects/_file_form.html.twig') }}
    </div>
{% endblock %}

templates/projects/filter.html.twig
{% extends 'base.html.twig' %}

{% set hasNavTabs = true %}

{% block title %}Projets{% endblock %}

{% block navTabs %}
    {{ include('partials/_project_index_header.html.twig') }}
{% endblock %}

{% block body %}
    <main class="w-75 mx-auto mt-5">
        <h2 class="h1 mb-5">{{ filter.label }}</h2>

        <hr class="col-3 col-md-2 mb-5">

        <div class="row">
            {% for project in projects %}
                {{ include('partials/project/_project_card.html.twig') }}
            {% else %}
                <h3 class="text-warning">Aucun projet n'est {{ filter.label | lower }}.</h3>
            {% endfor %}
        </div>
    </main>
{% endblock %}

templates/projects/member_add.html.twig
{% extends 'base.html.twig' %}

{% set hasNavTabs = true %}

{% block title %}{{ project.uid }} — {{ project.title }}{% endblock %}

{% block navTabs %}
    {{ include('partials/_project_nav_header.html.twig') }}
{% endblock %}

{% block body %}
    <div class="w-75 mx-auto mt-5">
        <h2 class="h1 mb-5">Ajouter un membre</h2>
        {{ include('projects/_member_form.html.twig') }}
    </div>
{% endblock %}

templates/projects/member_edit.html.twig
{% extends 'base.html.twig' %}

{% set hasNavTabs = true %}

{% block title %}{{ project.uid }} — {{ project.title }}{% endblock %}

{% block navTabs %}
    {{ include('partials/_project_nav_header.html.twig') }}
{% endblock %}

{% block body %}
    <div class="w-75 mx-auto mt-5">
        <h2 class="h1 mb-5">Modifier {{ member }}</h2>
        {{ form_start(form) }}
            {{ form_row(form.title) }}
            {{ form_row(form.isProjectManager) }}
            <button class="btn btn-primary">Enregistrer</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/projects/show.html.twig
{% extends 'base.html.twig' %}

{% set hasNavTabs = true %}

{% block title %}{{ project.uid }} — {{ project.title }}{% endblock %}

{% block navTabs %}
    {{ include('partials/_project_nav_header.html.twig') }}
{% endblock %}

{% dump(app.request) %}

{% block body %}
    <main class="w-75 mx-auto mt-5">
        <h2 class="h1 mb-5">Informations</h2>
        <h3 class="h3">{{ project.title }}</h3>
        <p class="fs-5 col-md-8">{{ project.description | nl2br }}</p>

        <hr class="col-3 col-md-2 mb-5">

        <div class="row g-5">
            <div class="col-md-6">
                <h2>Détails</h2>
                <p>Détails de la demande de mandat</p>
                <ul class="">
                    <li><strong>Date validée par le cahier des charges : </strong>{% if project.specificationsEndDate is defined %}{{ project.specificationsEndDate | date("d.m.Y") }}{% else %}<span class="text-danger">Aucune date validée</span>{% endif %}</li>
                    <li><strong>Date souhaitée : </strong>{{ project.mandate.desiredDate | date("d.m.Y") }}</li>
                    <li><strong>Client : </strong>{{ project.mandate.client }}</li>
                    <li><strong>Date de création : </strong>{{ project.mandate.createdAt | date("d.m.Y H:i") }}</li>
                </ul>
            </div>

            <div class="col-md-6">
                <h2>Fichiers</h2>
                <p>Voici les fichiers fournis par le client dans le but d'étailler ça demande de mandat.</p>
                <ul class="icon-list">
                    {% for file in project.mandate.files %}
                        <li><a href="{{vich_uploader_asset(file)}}">{{ file.title }}</a></li>
                    {% else %}
                        <li class="text-muted">Aucun fichier</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </main>
{% endblock %}

templates/projects/show_evaluations.html.twig
{% extends 'base.html.twig' %}

{% set hasNavTabs = true %}

{% block title %}{{ project.uid }} — {{ project.title }}{% endblock %}

{% block navTabs %}
    {{ include('partials/_project_nav_header.html.twig') }}
{% endblock %}

{% block body %}
    <div class="w-75 mx-auto mt-5">
        <h2 class="h1 mb-5">Évaluations</h2>

        <h4 class="h4 mt-5">Évaluation finale — Supérviseur</h4>
        <hr>
        <div class="list-group">
            {% for note in project.teacherEvaluation %}
                <div class="list-group-item d-flex justify-content-between align-items-start">
                <span class="text-warning">
                        {{ feather('file') }}
                </span>

                <span class="ms-2 me-auto">
                    <span class="fw-bold">{{ note.name }}</span><br>
                    <span class="text-muted">Données par {{ project.coach }}</span><br>
                </span>

                <div>
                    <span  class="badge bg-secondary">
                        {{ note.value }}
                    </span>
                </div>
                </div>
            {% else %}
                <div class="list-group-item d-flex justify-content-between align-items-start">
                <span class="text-danger">
                    {{ feather('x') }}
                </span>
                    <span class="ms-2 me-auto">
                    <span class="fw-bold">Aucune évaluation</span>
                </span>
                </div>
                {% if is_granted("FINAL_EVAL", project) %}
                <a href="{{ path('project.coach.evaluate', {'id': project.id}) }}" class="list-group-item d-flex justify-content-between align-items-start">
                <span class="text-success">
                    {{ feather('plus') }}
                </span>
                    <span class="ms-2 me-auto">
                    <span class="fw-bold">Évaluer maintenant</span>
                </span>
                </a>
                {% endif %}
            {% endfor %}

        </div>
        {% for member in project.members %}

        <h4 class="h4 mt-5">{{ member }}</h4>
        <hr>
        <div class="list-group">
            {% for evaluation in member.evaluations %}
                <div class="list-group-item d-flex justify-content-between align-items-start">
                <span class="text-warning">
                        {{ feather('file') }}
                </span>
                    <span class="ms-2 me-auto">
                    <span class="fw-bold">Évaluation du {{ evaluation.createdAt | date("d.m.Y") }}</span><br>
                    <span class="text-muted">Données par {{ evaluation.coach }}</span><br>
                </span>
                    <div>
                        {% for note in evaluation.notes %}
                        <span data-bs-toggle="tooltip" data-bs-placement="top" title="{{ note.name }}" class="badge bg-secondary">
                            {{ note.value }}
                        </span>
                        {% endfor %}
                    </div>
                </div>
            {% else %}
                <div class="list-group-item d-flex justify-content-between align-items-start">
                <span class="text-danger">
                    {{ feather('x') }}
                </span>
                    <span class="ms-2 me-auto">
                    <span class="fw-bold">Aucune évaluation</span>
                </span>
                </div>
            {% endfor %}
            <a href="{{ path('project.notes.student.new', {'id': member.id}) }}" class="list-group-item d-flex justify-content-between align-items-start">
                <span class="text-success">
                    {{ feather('plus') }}
                </span>
                <span class="ms-2 me-auto">
                    <span class="fw-bold">Ajouter une évaluation</span>
                </span>
            </a>
        </div>

        {% endfor %}

    </div>
{% endblock %}

templates/projects/show_milestones.html.twig
{% extends 'base.html.twig' %}

{% set hasNavTabs = true %}

{% block title %}{{ project.uid }} — {{ project.title }}{% endblock %}

{% block navTabs %}
    {{ include('partials/_project_nav_header.html.twig') }}
{% endblock %}

{% block body %}
    <div class="w-75 mx-auto mt-5">
        <h2 class="h1 mb-5">Jalons</h2>
        <div class="list-group">
            {% for milestone in project.milestones %}
            <div class="list-group-item d-flex justify-content-between align-items-start">
                {% if milestone.finished %}
                    <span class="text-success">
                        {{ feather('check-circle') }}
                    </span>
                {% else %}
                    <span class="text-warning">
                        {{ feather('circle') }}
                    </span>
                {% endif %}
                <span class="ms-2 me-auto">
                    <span class="fw-bold">{{ milestone.name }}</span><br>
                    <span class="text-muted">{{ milestone.stateLabel }} — Modifier le {{ milestone.updatedAt | date("d.m.Y à H:i") }}</span><br>
                    <span>{{ milestone.description }}</span>
                </span>
                {% if is_granted('SIMPLE_EDIT', project) %}
                    <a href="{{ path('project.edit.milestones', {id: project.id, milestoneID: milestone.id}) }}" class="btn btn-light text-dark">Modifier</a>
                {% endif %}
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/projects/show_settings.html.twig
{% extends 'base.html.twig' %}

{% set hasNavTabs = true %}

{% block title %}{{ project.uid }} — {{ project.title }}{% endblock %}

{% block navTabs %}
    {{ include('partials/_project_nav_header.html.twig') }}
{% endblock %}

{% block body %}
    <div class="w-75 mx-auto mt-5">
        <h2 class="h1 mb-5">Paramètres</h2>
        {{ form_start(form) }}
            {{ form_row(form.specificationsEndDate) }}
            {{ form_row(form.state) }}
            {{ form_row(form.coach) }}
            {{ form_row(form.class) }}
        <button class="btn btn-primary">Enregistrer</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/projects/show_teams.html.twig
{% extends 'base.html.twig' %}

{% set hasNavTabs = true %}

{% block title %}{{ project.uid }} — {{ project.title }}{% endblock %}

{% block navTabs %}
    {{ include('partials/_project_nav_header.html.twig') }}
{% endblock %}

{% block body %}
    <div class="w-75 mx-auto mt-5">
        <div class="d-flex justify-content-between align-items-center mb-5">
            <h2 class="h1">Équipe</h2>
            {% if is_granted('EDIT', project) %}
                <a href="{{ path('project.edit.add_member', {id: project.id})}}" class="btn btn-light text-dark">Ajouter un membre</a>
            {% endif %}
        </div>
        <div class="list-group">
            {% for member in project.members %}
                <div class="list-group-item d-flex justify-content-between align-items-center">
                    {% if member.isProjectManager %}
                        <span class="text-warning" data-bs-toggle="tooltip" data-bs-placement="top" title="Chef de projet">
                            {{ feather('zap') }}
                        </span>
                    {% endif %}
                    <span class="ms-2 me-auto">
                        <span class="fw-bold fs-5">{{ member }}</span><br>
                        {% if member.title is defined %}<span class="text-muted">{{ member.title }}</span>{% endif %}
                    </span>
                    {% if is_granted('EDIT', project) %}
                        <div class="hstack">
                            <a href="{{ path('project.edit.edit_member', {id: member.id}) }}" class="btn btn-sm btn-light text-dark">Modifier</a>
                            {{ include('projects/_delete_member_form.html.twig') }}
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/projects/student-evaluation_add.html.twig
{% extends 'base.html.twig' %}

{% set hasNavTabs = true %}
{% form_theme form 'bootstrap_5_horizontal_layout.html.twig' %}

{% block title %}{{ project.uid }} — {{ project.title }}{% endblock %}

{% block navTabs %}
    {{ include('partials/_project_nav_header.html.twig') }}
{% endblock %}

{% block body %}
    <div class="w-75 mx-auto mt-5">
        <h2 class="h1 mb-5">Nouvelle évaluation pour {{ member }}</h2>
        {{ form_start(form, ) }}
            {% for note in form.notes %}
                <fieldset>
                    <legend>{{ note.name.vars.value }}</legend>
                    {{ form_row(note.name) }}
                    {{ form_row(note.value) }}
                    {{ form_row(note.comment) }}
                </fieldset>
            {% endfor %}
        <button class="btn btn-primary">Enregistrer</button>
        {{ form_end(form) }}
    </div>
{% endblock %}