src/Entity/User.php
<?php

namespace App\Entity;

use App\Helper\StringFormat;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this username')]
#[ORM\HasLifecycleCallbacks()]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    #[Assert\Email()]
    private $email;

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\OneToOne(inversedBy: 'user', targetEntity: Person::class, cascade: ['persist', 'remove'])]
    private $person;

    #[ORM\ManyToMany(targetEntity: Role::class, inversedBy: 'users')]
    private $roles;

    #[ORM\Column(type: 'datetime_immutable')]
    private $createdAt;

    #[ORM\Column(type: 'datetime_immutable')]
    private $updatedAt;

    #[ORM\ManyToOne(targetEntity: self::class, cascade: ["persist"])]
    #[ORM\JoinColumn(onDelete: "SET NULL")]
    private $updatedBy;

    #[ORM\OneToMany(mappedBy: 'createdBy', targetEntity: Project::class)]
    private $createdProjects;

    #[ORM\OneToMany(mappedBy: 'updatedBy', targetEntity: Project::class)]
    private $updatedProjects;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Member::class)]
    private $memberships;

    #[ORM\OneToMany(mappedBy: 'createdBy', targetEntity: File::class)]
    private $files;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private $bannedAt;


    public function __construct()
    {
        $this->setCreatedAt(new \DateTimeImmutable());
        $this->setUpdatedAt(new \DateTimeImmutable());
        $this->roles = new ArrayCollection();
        $this->createdProjects = new ArrayCollection();
        $this->updatedProjects = new ArrayCollection();
        $this->memberships = new ArrayCollection();
        $this->files = new ArrayCollection();
    }

    /**
     * @ORM\PreUpdate()
     */
    public function onPreUpdate()
    {
        $this->setUpdatedAt(new \DateTimeImmutable());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail($email)
    {
       $this->email = $email;
       return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getPerson(): ?Person
    {
        return $this->person;
    }

    public function setPerson(?Person $person): self
    {
        $this->person = $person;

        return $this;
    }

    public function getRoles(): array
    {
        $roles = [];
        $roles[] = "ROLE_USER";
         foreach ($this->roles as $role) {
            $roles[] = $role->getSlug();
        }
        return $roles;
    }

    public function getRoleString()
    {
        return StringFormat::CSV($this->getRoles());
    }

    public function addRole(Role $role): self
    {
        if (!$this->roles->contains($role)) {
            $this->roles[] = $role;
        }

        return $this;
    }

    public function removeRole(Role $role): self
    {
        $this->roles->removeElement($role);

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getUpdatedBy(): ?self
    {
        return $this->updatedBy;
    }

    public function setUpdatedBy(?self $updatedBy): self
    {
        $this->updatedBy = $updatedBy;

        return $this;
    }

    public function __toString(): string
    {
        return $this->getFullname();
    }

    /**
     * @return Collection<int, Project>
     */
    public function getCreatedProjects(): Collection
    {
        return $this->createdProjects;
    }

    public function addCreatedProject(Project $project): self
    {
        if (!$this->createdProjects->contains($project)) {
            $this->createdProjects[] = $project;
            $project->setCreatedBy($this);
        }

        return $this;
    }

    public function removeCreatedProject(Project $project): self
    {
        if ($this->createdProjects->removeElement($project)) {
            // set the owning side to null (unless already changed)
            if ($project->getCreatedBy() === $this) {
                $project->setCreatedBy(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Project>
     */
    public function getUpdatedProjects(): Collection
    {
        return $this->updatedProjects;
    }

    public function addUpdatedProject(Project $updatedProject): self
    {
        if (!$this->updatedProjects->contains($updatedProject)) {
            $this->updatedProjects[] = $updatedProject;
            $updatedProject->setUpdatedBy($this);
        }

        return $this;
    }

    public function removeUpdatedProject(Project $updatedProject): self
    {
        if ($this->updatedProjects->removeElement($updatedProject)) {
            // set the owning side to null (unless already changed)
            if ($updatedProject->getUpdatedBy() === $this) {
                $updatedProject->setUpdatedBy(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Member>
     */
    public function getMemberships(): Collection
    {
        return $this->memberships;
    }

    public function addMembership(Member $membership): self
    {
        if (!$this->memberships->contains($membership)) {
            $this->memberships[] = $membership;
            $membership->setUser($this);
        }

        return $this;
    }

    public function removeMembership(Member $membership): self
    {
        if ($this->memberships->removeElement($membership)) {
            // set the owning side to null (unless already changed)
            if ($membership->getUser() === $this) {
                $membership->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Project[]
     */
    public function getProjects(): array
    {
        $projects = [];

        foreach ($this->getMemberships() as $membership) {
            $projects[] = $membership->getProject();
        }

        return $projects;
    }


    /**
     * @return Collection<int, File>
     */
    public function getFiles(): Collection
    {
        return $this->files;
    }

    public function addFile(File $file): self
    {
        if (!$this->files->contains($file)) {
            $this->files[] = $file;
            $file->setCreatedBy($this);
        }

        return $this;
    }

    public function removeFile(File $file): self
    {
        if ($this->files->removeElement($file)) {
            // set the owning side to null (unless already changed)
            if ($file->getCreatedBy() === $this) {
                $file->setCreatedBy(null);
            }
        }

        return $this;
    }


    /**
     * Data from related Person entity
     */

    public function getFirstname(): ?string
    {
        return $this->getPerson()->getFirstname();
    }

    public function getLastname(): ?string
    {
        return $this->getPerson()->getLastname();
    }

    public function getFullname(): string
    {
        return $this->getFirstname() . " " . $this->getLastname();
    }

    public function getClass(): ?Classe
    {
        return $this->getPerson()->getClass();
    }

    public function getType(): PersonType
    {
        return $this->getPerson()->getType();
    }

    public function isDirector(): bool
    {
        return $this->getPerson()->isDirector();
    }

    public function getBannedAt(): ?\DateTimeImmutable
    {
        return $this->bannedAt;
    }

    public function setBannedAt(?\DateTimeImmutable $bannedAt): self
    {
        $this->bannedAt = $bannedAt;

        return $this;
    }

    public function isBanned()
    {
        return !is_null($this->getBannedAt());
    }

}

templates/front/pages/home.html.twig
{% extends 'app_base.html.twig' %}

{% block body %}
    <div class="container">
        <div>
            <div class="header">
                <h1>Que souhaitez-vous faire ?</h1>
            </div>
            <div class="body">
                <nav>
                    {% if not is_granted("IS_AUTHENTICATED_FULLY") %}
                    <a class="nav-item" href="{{ path('security.login') }}">
                        <span class="icon">{{ feather('log-in') }}</span>
                        <span class="nav-item__text">Me connecter</span>
                    </a>

                    <a class="nav-item" href="{{ path('security.register_client') }}">
                        <span class="icon">{{ feather('edit-2') }}</span>
                        <span class="nav-item__text">Devenir client</span>
                    </a>
                    {% endif %}

                    {% if is_granted('ROLE_CLIENT') %}
                    <a class="nav-item" href="{{ path('app.client.index') }}">
                        <span class="icon">{{ feather('book') }}</span>
                        <span class="nav-item__text">Mes mandats</span>
                    </a>{#
                    <a class="nav-item" href="#">
                        <span class="icon">{{ feather('zap') }}</span>
                        <span class="nav-item__text">Afficher un mandat</span>
                    </a>#}
                    {% endif %}

                    {% if is_granted('ROLE_CLIENT') or is_granted('ROLE_CPNV') %}
                    <a class="nav-item" href="{{ path('app.client.new_mandate') }}">
                        <span class="icon">{{ feather('award') }}</span>
                        <span class="nav-item__text">Accéder au formulaire de demande de mandat</span>
                    </a>
                    {% endif %}

                    {% if is_granted("ROLE_CPNV") %}
                    <a class="nav-item" data-turbo="false" href="{{ path('panel.home') }}">
                        <span class="icon">{{ feather('activity') }}</span>
                        <span class="nav-item__text">Accéder au panel</span>
                    </a>
                    {% endif %}

                    {% if is_granted("IS_AUTHENTICATED_FULLY") %}
                        <a class="nav-item" href="{{ path('security.logout') }}">
                            <span class="icon">{{ feather('log-out') }}</span>
                            <span class="nav-item__text">Se déconnecter</span>
                        </a>
                    {% endif %}
                </nav>
            </div>
        </div>
        <div class="gradient-bg">
            <div class="header">
                <p class="text-muted">Bienvenue sur</p>
                <h2>L’application de gestion des projets de la Junior Entreprise</h2>
            </div>
            <div class="body">
                <p class="mb4">Cette application est à destination des</p>
                <div class="stylized-list ml2">
                    <div class="list-item">
                        <div class="icon">{{ feather('tool') }}</div>
                        <p>Étudiants <span class="text-muted">en médiamatique du CPNV de Ste-Croix de 3e année, afin d’accéder à la gestion de leurs différents projets.</span></p>
                    </div>

                    <div class="list-item">
                        <div class="icon">{{ feather('activity') }}</div>
                        <p>Clients <span class="text-muted">afin d’accéder au suivi de leurs différents projets. Ainsi qu’à effectuer des demandes de mandat.</span></p>
                    </div>

                    <div class="list-item">
                        <div class="icon">{{ feather('shield') }}</div>
                        <p>Enseignants <span class="text-muted">afin de suivre et d'assister les étudiants dans leurs différentes tâches. Ainsi qu'à gérer la réception des nouvelles demandes de mandat.</span></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/front/pages/mandate_form.html.twig
{% extends 'app_base.html.twig' %}


{% form_theme form 'form/custom_layout.html.twig' %}

{% block body %}
    <div class="container">
        <div>
            <div class="header">
                <a href="{{ path('app.home') }}" class="btn-back">{{ feather('chevron-left') }} Retour</a>
                <h1>Demande de mandat</h1>
            </div>
            <div class="body">
                {{ form_start(form) }}
                <div class="stack">
                    <h2>Informations professionnelles</h2>
                    {{ form_row(form.title) }}
                    {{ form_row(form.description) }}
                    {{ form_row(form.desiredDate) }}
                    {{ form_row(form.documentFiles) }}
                </div>
                <button class="btn-primary btn-block mt2">Envoyer ma demande</button>
                {{ form_end(form) }}
            </div>
        </div>
        <div class="gradient-bg">
            <div class="header">
                <p class="text-muted">Bienvenue sur</p>
                <h2>L’application de gestion des projets de la Junior Entreprise</h2>
            </div>
            <div class="body">
                <p class="mb4">Cette application est à destination des</p>
                <div class="stylized-list ml2">
                    <div class="list-item">
                        <div class="icon">{{ feather('tool') }}</div>
                        <p>Étudiants <span class="text-muted">en médiamatique du CPNV de Ste-Croix de 3e année, afin d’accéder à la gestion de leurs différents projets.</span></p>
                    </div>

                    <div class="list-item">
                        <div class="icon">{{ feather('activity') }}</div>
                        <p>Clients <span class="text-muted">afin d’accéder au suivi de leurs différents projets. Ainsi qu’à effectuer des demandes de mandat.</span></p>
                    </div>

                    <div class="list-item">
                        <div class="icon">{{ feather('shield') }}</div>
                        <p>Enseignants <span class="text-muted">afin de suivre et d'assister les étudiants dans leurs différentes tâches. Ainsi qu'à gérer la réception des nouvelles demandes de mandat.</span></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/front/pages/register.html.twig
{% extends 'app_base.html.twig' %}


{% form_theme form 'form/custom_layout.html.twig' %}

{% block body %}
    <div class="container">
        <div>
            <div class="header">
                <h1>Devenir client</h1>
            </div>
            <div class="body">
                {{ form_start(form, {attr: {"data-turbo": "false"}}) }}
                <div class="stack">
                    <h2>Informations professionnelles</h2>
                    {{ form_row(form.person.firstname) }}
                    {{ form_row(form.person.lastname) }}
                    {{ form_row(form.person.client.phoneNumber) }}
                    {{ form_row(form.person.client.company) }}
                    {{ form_row(form.person.client.contact) }}

                    <h2 class="mt2">Informations personnelles</h2>
                    {{ form_row(form.email) }}
                    {{ form_row(form.plainPassword) }}
                    {{ form_row(form.agreeTerms) }}
                </div>
                <button class="btn-primary btn-block mt2">S'inscrire</button>
                {{ form_end(form) }}
            </div>
        </div>
        <div class="gradient-bg">
            <div class="header">
                <p class="text-muted">Bienvenue sur</p>
                <h2>L’application de gestion des projets de la Junior Entreprise</h2>
            </div>
            <div class="body">
                <p class="mb4">Cette application est à destination des</p>
                <div class="stylized-list ml2">
                    <div class="list-item">
                        <div class="icon">{{ feather('tool') }}</div>
                        <p>Étudiants <span class="text-muted">en médiamatique du CPNV de Ste-Croix de 3e année, afin d’accéder à la gestion de leurs différents projets.</span></p>
                    </div>

                    <div class="list-item">
                        <div class="icon">{{ feather('activity') }}</div>
                        <p>Clients <span class="text-muted">afin d’accéder au suivi de leurs différents projets. Ainsi qu’à effectuer des demandes de mandat.</span></p>
                    </div>

                    <div class="list-item">
                        <div class="icon">{{ feather('shield') }}</div>
                        <p>Enseignants <span class="text-muted">afin de suivre et d'assister les étudiants dans leurs différentes tâches. Ainsi qu'à gérer la réception des nouvelles demandes de mandat.</span></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}